version: "3"
services:
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.production
    restart: unless-stopped
    mem_limit: 512m # Limit memory usage to 512MB
    mem_reservation: 256m # Soft limit, container will try to stay around 256MB
