version: "3.8"

services:
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./frontend/.env.local:/app/.env.local
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev
