import Image from "next/image";

export default function Home() {
  return (
    <div>
      <h1>ShellHacks 2024</h1>
      <p>Generated by create next app.</p>
      <Image src="/vercel.svg" alt="Vercel Logo" width={283} height={64} />
    </div>
  );
}
