export default function Home() {
  return (
    <div>
      <h1>ShellHacks 2024</h1>
      <p>Generated by create next app.</p>
      <a href="/api/auth/login">Login</a>
      <a href="/api/auth/logout">Logout</a>
    </div>
  );
}
