// * Home Page
// Deploy 1.0.6
export default function Home() {
  // No one should see this page until we create a public landing page
  return (
    <div className="flex flex-col spacing-y-4">
      <h1>ShellHacks 2024</h1>
      <p>Generated by create next app.</p>
      <a href="/api/auth/login">Login</a>
      <a href="/api/auth/logout">Logout</a>
    </div>
  );
}
